// <auto-generated />
using System;
using DoorsWebProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoorsWebProject.Data.Migrations
{
    [DbContext(typeof(DoorsDbContext))]
    [Migration("20250809210654_SeedDoorsWithDifferentTypes")]
    partial class SeedDoorsWithDifferentTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoorsWebProject.Data.Models.ApplicationUserDoor", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Foreign key to the referenced AspNetUser. Part of the entity composite PK");

                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced Door. Part of the entity composite PK");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Show if ApplicationUserDoor entry is deleted");

                    b.HasKey("ApplicationUserId", "DoorId");

                    b.HasIndex("DoorId");

                    b.ToTable("ApplicationUserDoors", t =>
                        {
                            t.HasComment("User Watchlist entry in the system");
                        });
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Basket", b =>
                {
                    b.Property<Guid>("BasketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BasketId");

                    b.HasIndex("UserId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.BasketItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BasketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("DoorId");

                    b.ToTable("BasketItems");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Color", b =>
                {
                    b.Property<Guid>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NameColor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Door", b =>
                {
                    b.Property<Guid>("DoorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Thickness")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DoorId");

                    b.ToTable("Doors");

                    b.HasData(
                        new
                        {
                            DoorId = new Guid("11111111-aaaa-4bbb-cccc-000000000002"),
                            Description = "Smooth steel door with minimalist style.",
                            Height = 210.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-smooth-steel-door.webp",
                            IsDeleted = false,
                            Material = "Steel",
                            Model = "S200",
                            Price = 529.99m,
                            Thickness = 4.0m,
                            Type = "Smooth",
                            Width = 95.0m
                        },
                        new
                        {
                            DoorId = new Guid("22222222-bbbb-4ccc-dddd-000000000003"),
                            Description = "Smooth steel door, ideal for modern apartments.",
                            Height = 205.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-smooth-2.webp",
                            IsDeleted = false,
                            Material = "Steel",
                            Model = "S250",
                            Price = 489.99m,
                            Thickness = 4.2m,
                            Type = "Smooth",
                            Width = 92.0m
                        },
                        new
                        {
                            DoorId = new Guid("33333333-cccc-4ddd-eeee-000000000004"),
                            Description = "Smooth aluminium door with matte finish.",
                            Height = 200.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-smooth-aluminium.webp",
                            IsDeleted = false,
                            Material = "Aluminium",
                            Model = "S300",
                            Price = 549.99m,
                            Thickness = 3.8m,
                            Type = "Smooth",
                            Width = 88.0m
                        },
                        new
                        {
                            DoorId = new Guid("44444444-dddd-4eee-ffff-000000000005"),
                            Description = "Profiled steel door with decorative panels.",
                            Height = 215.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-profiled-steel-door.webp",
                            IsDeleted = false,
                            Material = "Steel",
                            Model = "P100",
                            Price = 599.99m,
                            Thickness = 4.5m,
                            Type = "Profiled",
                            Width = 96.0m
                        },
                        new
                        {
                            DoorId = new Guid("55555555-eeee-4fff-aaaa-000000000006"),
                            Description = "Profiled steel door with elegant frame.",
                            Height = 210.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-profiled-2.webp",
                            IsDeleted = false,
                            Material = "Steel",
                            Model = "P150",
                            Price = 569.99m,
                            Thickness = 4.3m,
                            Type = "Profiled",
                            Width = 94.0m
                        },
                        new
                        {
                            DoorId = new Guid("66666666-ffff-4aaa-bbbb-000000000007"),
                            Description = "Profiled wooden door with traditional design.",
                            Height = 205.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-profiled-wood.webp",
                            IsDeleted = false,
                            Material = "Wood",
                            Model = "P200",
                            Price = 649.99m,
                            Thickness = 4.0m,
                            Type = "Profiled",
                            Width = 90.0m
                        },
                        new
                        {
                            DoorId = new Guid("77777777-aaaa-4bbb-cccc-000000000008"),
                            Description = "Profiled aluminium door with brushed surface.",
                            Height = 200.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-profiled-aluminium.webp",
                            IsDeleted = false,
                            Material = "Aluminium",
                            Model = "P250",
                            Price = 589.99m,
                            Thickness = 3.7m,
                            Type = "Profiled",
                            Width = 88.0m
                        },
                        new
                        {
                            DoorId = new Guid("88888888-bbbb-4ccc-dddd-000000000009"),
                            Description = "Glazed steel door with tempered glass panel.",
                            Height = 215.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-glazed-steel-door.webp",
                            IsDeleted = false,
                            Material = "Steel + Glass",
                            Model = "G100",
                            Price = 699.99m,
                            Thickness = 4.8m,
                            Type = "Glazed",
                            Width = 98.0m
                        },
                        new
                        {
                            DoorId = new Guid("99999999-cccc-4ddd-eeee-000000000010"),
                            Description = "Glazed steel door with frosted glass insert.",
                            Height = 210.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-glazed-2.webp",
                            IsDeleted = false,
                            Material = "Steel + Glass",
                            Model = "G150",
                            Price = 729.99m,
                            Thickness = 4.5m,
                            Type = "Glazed",
                            Width = 94.0m
                        },
                        new
                        {
                            DoorId = new Guid("aaaaaaaa-dddd-4eee-ffff-000000000011"),
                            Description = "Glazed wooden door with decorative glass.",
                            Height = 205.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-glazed-wood.webp",
                            IsDeleted = false,
                            Material = "Wood + Glass",
                            Model = "G200",
                            Price = 759.99m,
                            Thickness = 4.2m,
                            Type = "Glazed",
                            Width = 92.0m
                        },
                        new
                        {
                            DoorId = new Guid("bbbbbbbb-eeee-4fff-aaaa-000000000012"),
                            Description = "Smooth luxury steel door with premium coating.",
                            Height = 220.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-smooth-lux.webp",
                            IsDeleted = false,
                            Material = "Steel",
                            Model = "S350",
                            Price = 599.99m,
                            Thickness = 4.7m,
                            Type = "Smooth",
                            Width = 100.0m
                        },
                        new
                        {
                            DoorId = new Guid("cccccccc-ffff-4aaa-bbbb-000000000013"),
                            Description = "Profiled steel door with ornate panel design.",
                            Height = 210.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-profiled-lux.webp",
                            IsDeleted = false,
                            Material = "Steel",
                            Model = "P300",
                            Price = 639.99m,
                            Thickness = 4.5m,
                            Type = "Profiled",
                            Width = 95.0m
                        },
                        new
                        {
                            DoorId = new Guid("dddddddd-aaaa-4bbb-cccc-000000000014"),
                            Description = "Modern glazed door with clear glass panel.",
                            Height = 215.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-glazed-modern.webp",
                            IsDeleted = false,
                            Material = "Steel + Glass",
                            Model = "G250",
                            Price = 749.99m,
                            Thickness = 4.6m,
                            Type = "Glazed",
                            Width = 96.0m
                        },
                        new
                        {
                            DoorId = new Guid("eeeeeeee-bbbb-4ccc-dddd-000000000015"),
                            Description = "Ultra-smooth aluminium door for contemporary homes.",
                            Height = 205.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-smooth-ultra.webp",
                            IsDeleted = false,
                            Material = "Aluminium",
                            Model = "S400",
                            Price = 559.99m,
                            Thickness = 4.0m,
                            Type = "Smooth",
                            Width = 93.0m
                        },
                        new
                        {
                            DoorId = new Guid("ffffffff-cccc-4ddd-eeee-000000000016"),
                            Description = "Classic profiled wooden door with deep carvings.",
                            Height = 215.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-profiled-classic.webp",
                            IsDeleted = false,
                            Material = "Wood",
                            Model = "P350",
                            Price = 689.99m,
                            Thickness = 4.4m,
                            Type = "Profiled",
                            Width = 98.0m
                        },
                        new
                        {
                            DoorId = new Guid("12345678-dddd-4eee-ffff-000000000017"),
                            Description = "Luxury glazed aluminium door with tinted glass.",
                            Height = 220.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-glazed-lux.webp",
                            IsDeleted = false,
                            Material = "Aluminium + Glass",
                            Model = "G300",
                            Price = 799.99m,
                            Thickness = 4.9m,
                            Type = "Glazed",
                            Width = 100.0m
                        },
                        new
                        {
                            DoorId = new Guid("23456789-eeee-4fff-aaaa-000000000018"),
                            Description = "Smooth steel door with advanced security locks.",
                            Height = 210.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-smooth-secure.webp",
                            IsDeleted = false,
                            Material = "Steel",
                            Model = "S450",
                            Price = 629.99m,
                            Thickness = 4.6m,
                            Type = "Smooth",
                            Width = 95.0m
                        },
                        new
                        {
                            DoorId = new Guid("34567890-ffff-4aaa-bbbb-000000000019"),
                            Description = "Profiled steel door reinforced for extra security.",
                            Height = 210.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-profiled-secure.webp",
                            IsDeleted = false,
                            Material = "Steel",
                            Model = "P400",
                            Price = 669.99m,
                            Thickness = 4.5m,
                            Type = "Profiled",
                            Width = 94.0m
                        },
                        new
                        {
                            DoorId = new Guid("45678901-aaaa-4bbb-cccc-000000000020"),
                            Description = "Secure glazed steel door with impact-resistant glass.",
                            Height = 215.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-glazed-secure.webp",
                            IsDeleted = false,
                            Material = "Steel + Glass",
                            Model = "G350",
                            Price = 789.99m,
                            Thickness = 4.8m,
                            Type = "Glazed",
                            Width = 97.0m
                        },
                        new
                        {
                            DoorId = new Guid("56789012-bbbb-4ccc-dddd-000000000021"),
                            Description = "Eco-friendly smooth aluminium door with insulation.",
                            Height = 205.0m,
                            ImageUrl = "https://starkdoor.com/external/public_html/images/categories/stark-smooth-eco.webp",
                            IsDeleted = false,
                            Material = "Aluminium",
                            Model = "S500",
                            Price = 579.99m,
                            Thickness = 4.1m,
                            Type = "Smooth",
                            Width = 92.0m
                        });
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.DoorCategory", b =>
                {
                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DoorId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("DoorCategory");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.DoorColor", b =>
                {
                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DoorId", "ColorId");

                    b.HasIndex("ColorId");

                    b.ToTable("DoorColor");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.DoorWishlist", b =>
                {
                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DoorId", "WishlistId");

                    b.HasIndex("WishlistId");

                    b.ToTable("DoorWishlist");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Wishlist", b =>
                {
                    b.Property<Guid>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WishlistId");

                    b.HasIndex("UserId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.ApplicationUserDoor", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Door", "Door")
                        .WithMany("UserWishlists")
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Door");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Basket", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.BasketItem", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.Basket", null)
                        .WithMany("BasketDoors")
                        .HasForeignKey("BasketId");

                    b.HasOne("DoorsWebProject.Data.Models.Door", "Door")
                        .WithMany("DoorBaskets")
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Door");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.DoorCategory", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.Category", "Category")
                        .WithMany("CategoryDoors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Door", "Door")
                        .WithMany("DoorCategories")
                        .HasForeignKey("DoorId");

                    b.Navigation("Category");

                    b.Navigation("Door");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.DoorColor", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.Color", "Color")
                        .WithMany("ColorDoors")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Door", "Door")
                        .WithMany("DoorColors")
                        .HasForeignKey("DoorId");

                    b.Navigation("Color");

                    b.Navigation("Door");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.DoorWishlist", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.Door", "Door")
                        .WithMany("DoorWishlists")
                        .HasForeignKey("DoorId");

                    b.HasOne("DoorsWebProject.Data.Models.Wishlist", "Wishlist")
                        .WithMany("WishlistDoors")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Door");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Wishlist", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Basket", b =>
                {
                    b.Navigation("BasketDoors");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Category", b =>
                {
                    b.Navigation("CategoryDoors");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Color", b =>
                {
                    b.Navigation("ColorDoors");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Door", b =>
                {
                    b.Navigation("DoorBaskets");

                    b.Navigation("DoorCategories");

                    b.Navigation("DoorColors");

                    b.Navigation("DoorWishlists");

                    b.Navigation("UserWishlists");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Wishlist", b =>
                {
                    b.Navigation("WishlistDoors");
                });
#pragma warning restore 612, 618
        }
    }
}
