// <auto-generated />
using System;
using DoorsWebProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoorsWebProject.Data.Migrations
{
    [DbContext(typeof(DoorsDbContext))]
    [Migration("20260304133803_ModifiedDoorObject")]
    partial class ModifiedDoorObject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoorsWebProject.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.ApplicationUserDoor", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Foreign key to the referenced AspNetUser. Part of the entity composite PK");

                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced Door. Part of the entity composite PK");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Show if ApplicationUserDoor entry is deleted");

                    b.HasKey("ApplicationUserId", "DoorId");

                    b.HasIndex("DoorId");

                    b.ToTable("ApplicationUserDoors", t =>
                        {
                            t.HasComment("User Watchlist entry in the system");
                        });
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Basket", b =>
                {
                    b.Property<Guid>("BasketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("BasketId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.BasketDetail", b =>
                {
                    b.Property<Guid>("BasketDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BasketDetailId");

                    b.HasIndex("BasketId");

                    b.HasIndex("DoorId");

                    b.ToTable("BasketDetails");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Color", b =>
                {
                    b.Property<Guid>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NameColor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TextureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ColorId = new Guid("2b90c521-fe5c-4d18-b529-eb9f2b545efb"),
                            HexCode = "#D8B589",
                            IsDeleted = false,
                            NameColor = "Дъб",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("0f65c147-aa61-495e-a597-963b6ee6a36c"),
                            HexCode = "#42291A",
                            IsDeleted = false,
                            NameColor = "Орех",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("d9f1e7c2-69ea-442c-8284-42f6343f0898"),
                            HexCode = "#645452",
                            IsDeleted = false,
                            NameColor = "Венге",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("649f1a32-4928-48b2-947d-599df8748d6f"),
                            HexCode = "#F1C38E",
                            IsDeleted = false,
                            NameColor = "Явор",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("65a39814-a1cc-4a57-96e2-4afc22fd4d2a"),
                            HexCode = "#A48071",
                            IsDeleted = false,
                            NameColor = "Ясен",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("f5483f5f-9fc3-4651-8c2b-637eebabfa8f"),
                            HexCode = "#FFFFFF",
                            IsDeleted = false,
                            NameColor = "Бяло",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("4c462fcc-14b2-4af1-8c54-dbb6db5b15dc"),
                            HexCode = "#B5833D",
                            IsDeleted = false,
                            NameColor = "Златен дъб",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("e19eaf04-246f-4669-9a3e-a5158ba86306"),
                            HexCode = "#504c4b",
                            IsDeleted = false,
                            NameColor = "Сив дъб",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("43f687c1-3b7b-4611-833f-e11cf5c5e1f2"),
                            HexCode = "#7B2716",
                            IsDeleted = false,
                            NameColor = "Череша",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("48df69c8-8082-41a4-9a49-f76e66e3f1bc"),
                            HexCode = "#C04000",
                            IsDeleted = false,
                            NameColor = "Махагон",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("e099139e-4a0a-4c2b-a62e-45b5299f4ea9"),
                            HexCode = "#1a1818",
                            IsDeleted = false,
                            NameColor = "Черно",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("be968e0c-5802-4898-a60f-097fa2df63b5"),
                            HexCode = "#2E6F40",
                            IsDeleted = false,
                            NameColor = "Зелено",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("623c8827-062e-43a9-bc87-763c47363aba"),
                            HexCode = "#016388",
                            IsDeleted = false,
                            NameColor = "Синьо",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        });
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Door", b =>
                {
                    b.Property<Guid>("DoorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Thickness")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DoorId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Doors");

                    b.HasData(
                        new
                        {
                            DoorId = new Guid("40b2ed36-b35c-4016-b998-863038968490"),
                            ApplicationUserId = "b12cdb67-7ae7-4ae7-a7d0-22815749c41f",
                            Height = 200m,
                            ImageUrl = "https://galiardi.biz/wp-content/uploads/2019/01/t-100-africa-01-940834835-450x450.png",
                            IsDeleted = false,
                            Model = "А-101 Африка",
                            Price = 890.00m,
                            Thickness = 35m,
                            Type = "Armored",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("06ebf95c-7758-4ce2-afb3-191d3c57fe13"),
                            ApplicationUserId = "b12cdb67-7ae7-4ae7-a7d0-22815749c41f",
                            Height = 200m,
                            ImageUrl = "https://galiardi.biz/wp-content/uploads/2019/01/t-100-antik-01-552213818-450x450.png",
                            IsDeleted = false,
                            Model = "А-102-Антик",
                            Price = 835.00m,
                            Thickness = 35m,
                            Type = "Armored",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("55e5d4dc-a4fc-4fcd-aed1-4e688e63a547"),
                            ApplicationUserId = "bee1ccb1-7179-4d28-a154-2dbb5f88c189",
                            Height = 200m,
                            ImageUrl = "https://galiardi.biz/wp-content/uploads/2019/01/t-108-1228496364-450x450-300x300.png",
                            IsDeleted = false,
                            Model = "А-103-Орех",
                            Price = 800.00m,
                            Thickness = 35m,
                            Type = "Armored",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("eddf2e0d-ed9d-431b-90d1-8af284e5289b"),
                            ApplicationUserId = "bee1ccb1-7179-4d28-a154-2dbb5f88c189",
                            Height = 200m,
                            ImageUrl = "https://galiardi.biz/wp-content/uploads/2019/01/t-110-sparta-01-450x450.png",
                            IsDeleted = false,
                            Model = "А-104-Спарта",
                            Price = 870.00m,
                            Thickness = 35m,
                            Type = "Armored",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("e37f55fd-1f7b-40f2-9374-e881b95c4506"),
                            ApplicationUserId = "eef7fb7b-a155-419a-a7f7-6b6fc865ae03",
                            Height = 200m,
                            ImageUrl = "https://galiardi.biz/wp-content/uploads/2019/01/t-587-zebra-01-71555585-450x450.png",
                            IsDeleted = false,
                            Model = "А-105-Зебра",
                            Price = 900.00m,
                            Thickness = 35m,
                            Type = "Armored",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("ccc7397a-f7c6-46cd-9510-5dedb05a30f2"),
                            ApplicationUserId = "8b116c3a-c340-40e8-b6a3-a6b512e9fb2f",
                            Height = 200m,
                            ImageUrl = "https://www.idialvrati.com/cache/images/4509.jpg",
                            IsDeleted = false,
                            Model = "W-239-Синитово",
                            Price = 2500.00m,
                            Thickness = 35m,
                            Type = "Wooden",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("c09bac80-7531-49b3-b147-b8e0377ad093"),
                            ApplicationUserId = "eef7fb7b-a155-419a-a7f7-6b6fc865ae03",
                            Height = 200m,
                            ImageUrl = "https://www.idialvrati.com/cache/images/4559.jpg",
                            IsDeleted = false,
                            Model = "W-238-Яна",
                            Price = 1200.00m,
                            Thickness = 35m,
                            Type = "Wooden",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("648047b3-6e61-4932-9f22-48792f58b911"),
                            ApplicationUserId = "eef7fb7b-a155-419a-a7f7-6b6fc865ae03",
                            Height = 200m,
                            ImageUrl = "https://www.idialvrati.com/cache/images/4556.jpg",
                            IsDeleted = false,
                            Model = "W-237-Лидия",
                            Price = 1300.00m,
                            Thickness = 35m,
                            Type = "Wooden",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("63ab936a-7fa3-4578-99f6-dcd8608baad1"),
                            ApplicationUserId = "8b116c3a-c340-40e8-b6a3-a6b512e9fb2f",
                            Height = 200m,
                            ImageUrl = "https://www.idialvrati.com/cache/images/4561.jpg",
                            IsDeleted = false,
                            Model = "W-236-Боряна",
                            Price = 1250.00m,
                            Thickness = 35m,
                            Type = "Wooden",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("ef13a19f-4149-4b92-92f9-bbd3d2ce5e53"),
                            ApplicationUserId = "8b116c3a-c340-40e8-b6a3-a6b512e9fb2f",
                            Height = 200m,
                            ImageUrl = "https://www.idialvrati.com/cache/images/4563.jpg",
                            IsDeleted = false,
                            Model = "W-235-Алина",
                            Price = 1280.00m,
                            Thickness = 35m,
                            Type = "Wooden",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("988fbb66-32b9-4dd0-8458-e0202b5c4816"),
                            ApplicationUserId = "8b116c3a-c340-40e8-b6a3-a6b512e9fb2f",
                            Height = 200m,
                            ImageUrl = "https://karabulev.eu/wp-content/uploads/2017/03/%D0%9B%D0%90%D0%9C%D0%98%D0%9D%D0%90%D0%A2_%D0%9E%D0%A0%D0%95%D0%A5-%D0%9A%D0%9E%D0%A0%D0%A1%D0%98%D0%9A%D0%90.png",
                            IsDeleted = false,
                            Model = "S-131",
                            Price = 635.00m,
                            Thickness = 35m,
                            Type = "Smooth",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("5fd5662d-99b7-4bee-b0dd-1c4f6837e387"),
                            ApplicationUserId = "8b116c3a-c340-40e8-b6a3-a6b512e9fb2f",
                            Height = 200m,
                            ImageUrl = "https://karabulev.eu/wp-content/uploads/2018/04/tech-dab-01-300-670.jpg",
                            IsDeleted = false,
                            Model = "S-132",
                            Price = 835.00m,
                            Thickness = 35m,
                            Type = "Smooth",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("ec7dce3e-9fb9-4857-9148-4ea9b776ba24"),
                            ApplicationUserId = "b12cdb67-7ae7-4ae7-a7d0-22815749c41f",
                            Height = 200m,
                            ImageUrl = "https://karabulev.eu/wp-content/uploads/2017/03/INTARZIA-1.png",
                            IsDeleted = false,
                            Model = "S-133",
                            Price = 915.00m,
                            Thickness = 35m,
                            Type = "Smooth",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("8b59a026-9c22-4e66-a5e5-f2eb2fe22663"),
                            ApplicationUserId = "b12cdb67-7ae7-4ae7-a7d0-22815749c41f",
                            Height = 200m,
                            ImageUrl = "https://karabulev.eu/wp-content/uploads/2017/03/0007color.jpg",
                            IsDeleted = false,
                            Model = "S-134",
                            Price = 805.00m,
                            Thickness = 35m,
                            Type = "Smooth",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("8e8904a5-de04-4f1e-a78b-6d24bd7ea78a"),
                            ApplicationUserId = "b12cdb67-7ae7-4ae7-a7d0-22815749c41f",
                            Height = 200m,
                            ImageUrl = "https://karabulev.eu/wp-content/uploads/2017/04/0000prestige.jpg",
                            IsDeleted = false,
                            Model = "S-135",
                            Price = 1280.00m,
                            Thickness = 35m,
                            Type = "Smooth",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("70552a44-2166-4aa2-a114-a40f7b31bdb9"),
                            ApplicationUserId = "8b116c3a-c340-40e8-b6a3-a6b512e9fb2f",
                            Height = 200m,
                            ImageUrl = "https://karabulev.eu/wp-content/uploads/2017/04/%D0%A7%D0%95%D0%A0%D0%95%D0%A8%D0%90-%D0%A0%D0%98%D0%9C.png",
                            IsDeleted = false,
                            Model = "P-651",
                            Price = 915.00m,
                            Thickness = 35m,
                            Type = "Profiled",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("3ba1296e-029f-42c0-8f43-414a6a3650bc"),
                            ApplicationUserId = "8b116c3a-c340-40e8-b6a3-a6b512e9fb2f",
                            Height = 200m,
                            ImageUrl = "https://karabulev.eu/wp-content/uploads/2017/04/0008europe.jpg",
                            IsDeleted = false,
                            Model = "P-652",
                            Price = 915.00m,
                            Thickness = 35m,
                            Type = "Profiled",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("c8f0a9bc-920c-4435-bf39-e2f462640b4b"),
                            ApplicationUserId = "eef7fb7b-a155-419a-a7f7-6b6fc865ae03",
                            Height = 200m,
                            ImageUrl = "https://karabulev.eu/wp-content/uploads/2017/04/%D0%92%D0%95%D0%9D%D0%95%D0%A6%D0%98%D0%AF-300-670.png",
                            IsDeleted = false,
                            Model = "P-653",
                            Price = 975.00m,
                            Thickness = 35m,
                            Type = "Profiled",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("1d6842c1-474f-4688-bdff-dc3abb83a3d2"),
                            ApplicationUserId = "eef7fb7b-a155-419a-a7f7-6b6fc865ae03",
                            Height = 200m,
                            ImageUrl = "https://karabulev.eu/wp-content/uploads/2017/04/%D0%96%D0%95%D0%9D%D0%95%D0%92%D0%90-%D0%AF%D0%A1%D0%95%D0%9D-1013-300-680.png",
                            IsDeleted = false,
                            Model = "P-654",
                            Price = 915.00m,
                            Thickness = 35m,
                            Type = "Profiled",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("2bc078ce-7786-4362-b936-1a0c21140201"),
                            ApplicationUserId = "eef7fb7b-a155-419a-a7f7-6b6fc865ae03",
                            Height = 200m,
                            ImageUrl = "https://karabulev.eu/wp-content/uploads/2017/04/LONDON-48-SINEMORETC-300-670.png",
                            IsDeleted = false,
                            Model = "P-655",
                            Price = 930.00m,
                            Thickness = 35m,
                            Type = "Profiled",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("c829575d-b139-4137-a8c9-4e1d22d35a53"),
                            ApplicationUserId = "8b116c3a-c340-40e8-b6a3-a6b512e9fb2f",
                            Height = 200m,
                            ImageUrl = "https://karabulev.eu/wp-content/uploads/2017/04/0002tetris.jpg",
                            IsDeleted = false,
                            Model = "G-951",
                            Price = 1300.00m,
                            Thickness = 35m,
                            Type = "Glazed",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("fb98b190-80d7-42fd-a0a4-d1421ea03970"),
                            ApplicationUserId = "bee1ccb1-7179-4d28-a154-2dbb5f88c189",
                            Height = 200m,
                            ImageUrl = "https://karabulev.eu/wp-content/uploads/2017/04/%D0%AF%D0%A1%D0%95%D0%9D-1013-storgozia14.png",
                            IsDeleted = false,
                            Model = "G-952",
                            Price = 1200.00m,
                            Thickness = 35m,
                            Type = "Glazed",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("d8738414-dbbe-465f-945b-492214473c3d"),
                            ApplicationUserId = "bee1ccb1-7179-4d28-a154-2dbb5f88c189",
                            Height = 200m,
                            ImageUrl = "https://karabulev.eu/wp-content/uploads/2017/04/%D0%A1%D0%98%D0%9B%D0%A3%D0%95%D0%A2-%D0%9E%D0%A0%D0%95%D0%A5-%D0%9B%D0%90%D0%93%D0%A3%D0%9D%D0%901.png",
                            IsDeleted = false,
                            Model = "G-953",
                            Price = 1080.00m,
                            Thickness = 35m,
                            Type = "Glazed",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("7099f6ff-e9a5-4204-bc0a-5abadc7e57d0"),
                            ApplicationUserId = "bee1ccb1-7179-4d28-a154-2dbb5f88c189",
                            Height = 200m,
                            ImageUrl = "https://karabulev.eu/wp-content/uploads/2017/04/%D0%9C%D0%9B%D0%90%D0%94%D0%9E%D0%A1%D0%A2-05%D0%90.png",
                            IsDeleted = false,
                            Model = "G-954",
                            Price = 1180.00m,
                            Thickness = 35m,
                            Type = "Glazed",
                            Width = 90m
                        },
                        new
                        {
                            DoorId = new Guid("20c499b1-ed63-4576-acba-1b9c61a66e2b"),
                            ApplicationUserId = "bee1ccb1-7179-4d28-a154-2dbb5f88c189",
                            Height = 200m,
                            ImageUrl = "https://karabulev.eu/wp-content/uploads/2017/04/%D0%9B%D0%95%D0%99%D0%94%D0%98-%D0%93%D0%9B%D0%90%D0%A1-300%D1%85600.png",
                            IsDeleted = false,
                            Model = "G-955",
                            Price = 1215.00m,
                            Thickness = 35m,
                            Type = "Glazed",
                            Width = 90m
                        });
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.DoorCategory", b =>
                {
                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DoorId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("DoorCategory");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.DoorColor", b =>
                {
                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DoorId", "ColorId");

                    b.HasIndex("ColorId");

                    b.ToTable("DoorColor");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("DoorId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.OrderStatus", b =>
                {
                    b.Property<Guid>("OrderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("OrderStatusId");

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.ApplicationUserDoor", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("WishlistDoors")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Door", "Door")
                        .WithMany("UserWishlists")
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Door");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Basket", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.BasketDetail", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.Basket", "Basket")
                        .WithMany()
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Door", "Door")
                        .WithMany("BasketDetail")
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Door");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Door", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.ApplicationUser", "User")
                        .WithMany("Doors")
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.DoorCategory", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.Category", "Category")
                        .WithMany("CategoryDoors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Door", "Door")
                        .WithMany("DoorCategories")
                        .HasForeignKey("DoorId");

                    b.Navigation("Category");

                    b.Navigation("Door");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.DoorColor", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.Color", "Color")
                        .WithMany("ColorDoors")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Door", "Door")
                        .WithMany("DoorColors")
                        .HasForeignKey("DoorId");

                    b.Navigation("Color");

                    b.Navigation("Door");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Order", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.OrderDetail", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.Door", "Door")
                        .WithMany("OrderDetail")
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Order", "Order")
                        .WithMany("OrderDetail")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Door");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Doors");

                    b.Navigation("WishlistDoors");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Category", b =>
                {
                    b.Navigation("CategoryDoors");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Color", b =>
                {
                    b.Navigation("ColorDoors");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Door", b =>
                {
                    b.Navigation("BasketDetail");

                    b.Navigation("DoorCategories");

                    b.Navigation("DoorColors");

                    b.Navigation("OrderDetail");

                    b.Navigation("UserWishlists");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Order", b =>
                {
                    b.Navigation("OrderDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
