// <auto-generated />
using System;
using DoorsWebProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoorsWebProject.Data.Migrations
{
    [DbContext(typeof(DoorsDbContext))]
    [Migration("20260109111947_updated-tables")]
    partial class updatedtables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoorsWebProject.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.ApplicationUserDoor", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Foreign key to the referenced AspNetUser. Part of the entity composite PK");

                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced Door. Part of the entity composite PK");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Show if ApplicationUserDoor entry is deleted");

                    b.HasKey("ApplicationUserId", "DoorId");

                    b.HasIndex("DoorId");

                    b.ToTable("ApplicationUserDoors", t =>
                        {
                            t.HasComment("User Watchlist entry in the system");
                        });
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Basket", b =>
                {
                    b.Property<Guid>("BasketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("BasketId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.BasketDetail", b =>
                {
                    b.Property<Guid>("BasketDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("BasketDetailId");

                    b.HasIndex("BasketId");

                    b.HasIndex("DoorId");

                    b.ToTable("BasketDetails");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Color", b =>
                {
                    b.Property<Guid>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NameColor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TextureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ColorId = new Guid("2b90c521-fe5c-4d18-b529-eb9f2b545efb"),
                            HexCode = "#D8B589",
                            IsDeleted = false,
                            NameColor = "Дъб",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("0f65c147-aa61-495e-a597-963b6ee6a36c"),
                            HexCode = "#42291A",
                            IsDeleted = false,
                            NameColor = "Орех",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("d9f1e7c2-69ea-442c-8284-42f6343f0898"),
                            HexCode = "#645452",
                            IsDeleted = false,
                            NameColor = "Венге",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("649f1a32-4928-48b2-947d-599df8748d6f"),
                            HexCode = "#F1C38E",
                            IsDeleted = false,
                            NameColor = "Явор",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("65a39814-a1cc-4a57-96e2-4afc22fd4d2a"),
                            HexCode = "#A48071",
                            IsDeleted = false,
                            NameColor = "Ясен",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("f5483f5f-9fc3-4651-8c2b-637eebabfa8f"),
                            HexCode = "#FFFFFF",
                            IsDeleted = false,
                            NameColor = "Бяло",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("4c462fcc-14b2-4af1-8c54-dbb6db5b15dc"),
                            HexCode = "#B5833D",
                            IsDeleted = false,
                            NameColor = "Златен дъб",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("e19eaf04-246f-4669-9a3e-a5158ba86306"),
                            HexCode = "#504c4b",
                            IsDeleted = false,
                            NameColor = "Сив дъб",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("43f687c1-3b7b-4611-833f-e11cf5c5e1f2"),
                            HexCode = "#7B2716",
                            IsDeleted = false,
                            NameColor = "Череша",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("48df69c8-8082-41a4-9a49-f76e66e3f1bc"),
                            HexCode = "#C04000",
                            IsDeleted = false,
                            NameColor = "Махагон",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("e099139e-4a0a-4c2b-a62e-45b5299f4ea9"),
                            HexCode = "#1a1818",
                            IsDeleted = false,
                            NameColor = "Черно",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("be968e0c-5802-4898-a60f-097fa2df63b5"),
                            HexCode = "#2E6F40",
                            IsDeleted = false,
                            NameColor = "Зелено",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        },
                        new
                        {
                            ColorId = new Guid("623c8827-062e-43a9-bc87-763c47363aba"),
                            HexCode = "#016388",
                            IsDeleted = false,
                            NameColor = "Синьо",
                            TextureUrl = "/textures/wooden-textured-background.jpg"
                        });
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Door", b =>
                {
                    b.Property<Guid>("DoorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Thickness")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DoorId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Doors");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.DoorCategory", b =>
                {
                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DoorId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("DoorCategory");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.DoorColor", b =>
                {
                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DoorId", "ColorId");

                    b.HasIndex("ColorId");

                    b.ToTable("DoorColor");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("DoorId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.OrderStatus", b =>
                {
                    b.Property<Guid>("OrderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("OrderStatusId");

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.ApplicationUserDoor", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("WishlistDoors")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Door", "Door")
                        .WithMany("UserWishlists")
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Door");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Basket", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.BasketDetail", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.Basket", "Basket")
                        .WithMany()
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Door", "Door")
                        .WithMany("BasketDetail")
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Door");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Door", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.ApplicationUser", "User")
                        .WithMany("Doors")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.DoorCategory", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.Category", "Category")
                        .WithMany("CategoryDoors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Door", "Door")
                        .WithMany("DoorCategories")
                        .HasForeignKey("DoorId");

                    b.Navigation("Category");

                    b.Navigation("Door");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.DoorColor", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.Color", "Color")
                        .WithMany("ColorDoors")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Door", "Door")
                        .WithMany("DoorColors")
                        .HasForeignKey("DoorId");

                    b.Navigation("Color");

                    b.Navigation("Door");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Order", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.OrderDetail", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.Door", "Door")
                        .WithMany("OrderDetail")
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Order", "Order")
                        .WithMany("OrderDetail")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Door");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Doors");

                    b.Navigation("WishlistDoors");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Category", b =>
                {
                    b.Navigation("CategoryDoors");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Color", b =>
                {
                    b.Navigation("ColorDoors");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Door", b =>
                {
                    b.Navigation("BasketDetail");

                    b.Navigation("DoorCategories");

                    b.Navigation("DoorColors");

                    b.Navigation("OrderDetail");

                    b.Navigation("UserWishlists");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Order", b =>
                {
                    b.Navigation("OrderDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
