// <auto-generated />
using System;
using AspNetCoreArchTemplate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoorsWebProject.Data.Migrations
{
    [DbContext(typeof(DoorsDbContext))]
    [Migration("20250623144942_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ColorDoor", b =>
                {
                    b.Property<Guid>("ColorsColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoorsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ColorsColorId", "DoorsId");

                    b.HasIndex("DoorsId");

                    b.ToTable("ColorDoor");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Basket", b =>
                {
                    b.Property<Guid>("BasketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BasketId");

                    b.ToTable("Baskets");

                    b.HasData(
                        new
                        {
                            BasketId = new Guid("11111111-aaaa-4bbb-8ccc-000000000001")
                        },
                        new
                        {
                            BasketId = new Guid("11111111-aaaa-4bbb-8ccc-000000000002")
                        },
                        new
                        {
                            BasketId = new Guid("11111111-aaaa-4bbb-8ccc-000000000003")
                        },
                        new
                        {
                            BasketId = new Guid("11111111-aaaa-4bbb-8ccc-000000000004")
                        },
                        new
                        {
                            BasketId = new Guid("11111111-aaaa-4bbb-8ccc-000000000005")
                        });
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3b9d5e1-8e5f-4f7b-9c88-bc6fbc761211"),
                            Name = "Security Doors"
                        },
                        new
                        {
                            Id = new Guid("b6e2f5c7-33dc-4c0e-920f-1a3fa7c6e9d2"),
                            Name = "Interior Doors"
                        },
                        new
                        {
                            Id = new Guid("c9f0a6d5-2344-45c2-bbe2-50d207b8573d"),
                            Name = "Exterior Doors"
                        },
                        new
                        {
                            Id = new Guid("d1a8e6c9-baf4-4e47-93d2-1cc9bcd69fe0"),
                            Name = "Fireproof Doors"
                        },
                        new
                        {
                            Id = new Guid("e3f7c1a4-39c3-43d3-8369-c1d267bb4371"),
                            Name = "Sliding Doors"
                        });
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Color", b =>
                {
                    b.Property<Guid>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Door", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("WishlistId");

                    b.ToTable("Doors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-cccc-4ddd-aaaa-000000000001"),
                            BasketId = new Guid("11111111-aaaa-4bbb-8ccc-000000000001"),
                            CategoryId = new Guid("a3b9d5e1-8e5f-4f7b-9c88-bc6fbc761211"),
                            Material = "Steel",
                            Model = "S100",
                            Price = 499.99m,
                            Size = "90x200 cm",
                            WishlistId = new Guid("22222222-bbbb-4ccc-9ddd-000000000001")
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-4ddd-aaaa-000000000002"),
                            BasketId = new Guid("11111111-aaaa-4bbb-8ccc-000000000002"),
                            CategoryId = new Guid("b6e2f5c7-33dc-4c0e-920f-1a3fa7c6e9d2"),
                            Material = "Oak Wood",
                            Model = "I200",
                            Price = 299.00m,
                            Size = "80x200 cm",
                            WishlistId = new Guid("22222222-bbbb-4ccc-9ddd-000000000002")
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-4ddd-aaaa-000000000003"),
                            BasketId = new Guid("11111111-aaaa-4bbb-8ccc-000000000003"),
                            CategoryId = new Guid("e3f7c1a4-39c3-43d3-8369-c1d267bb4371"),
                            Material = "Tempered Glass",
                            Model = "SL300",
                            Price = 399.50m,
                            Size = "100x210 cm",
                            WishlistId = new Guid("22222222-bbbb-4ccc-9ddd-000000000003")
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-4ddd-aaaa-000000000004"),
                            BasketId = new Guid("11111111-aaaa-4bbb-8ccc-000000000004"),
                            CategoryId = new Guid("d1a8e6c9-baf4-4e47-93d2-1cc9bcd69fe0"),
                            Material = "Steel with Fireproof Coating",
                            Model = "F400",
                            Price = 749.99m,
                            Size = "90x210 cm",
                            WishlistId = new Guid("22222222-bbbb-4ccc-9ddd-000000000004")
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-4ddd-aaaa-000000000005"),
                            BasketId = new Guid("11111111-aaaa-4bbb-8ccc-000000000005"),
                            CategoryId = new Guid("c9f0a6d5-2344-45c2-bbe2-50d207b8573d"),
                            Material = "Aluminum",
                            Model = "E500",
                            Price = 599.00m,
                            Size = "100x220 cm",
                            WishlistId = new Guid("22222222-bbbb-4ccc-9ddd-000000000005")
                        });
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Wishlist", b =>
                {
                    b.Property<Guid>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WishlistId");

                    b.ToTable("Wishlists");

                    b.HasData(
                        new
                        {
                            WishlistId = new Guid("22222222-bbbb-4ccc-9ddd-000000000001")
                        },
                        new
                        {
                            WishlistId = new Guid("22222222-bbbb-4ccc-9ddd-000000000002")
                        },
                        new
                        {
                            WishlistId = new Guid("22222222-bbbb-4ccc-9ddd-000000000003")
                        },
                        new
                        {
                            WishlistId = new Guid("22222222-bbbb-4ccc-9ddd-000000000004")
                        },
                        new
                        {
                            WishlistId = new Guid("22222222-bbbb-4ccc-9ddd-000000000005")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ColorDoor", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorsColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Door", null)
                        .WithMany()
                        .HasForeignKey("DoorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Door", b =>
                {
                    b.HasOne("DoorsWebProject.Data.Models.Basket", "Basket")
                        .WithMany("Doors")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Category", "Category")
                        .WithMany("Doors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorsWebProject.Data.Models.Wishlist", "Wishlist")
                        .WithMany("DoorList")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Category");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Basket", b =>
                {
                    b.Navigation("Doors");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Category", b =>
                {
                    b.Navigation("Doors");
                });

            modelBuilder.Entity("DoorsWebProject.Data.Models.Wishlist", b =>
                {
                    b.Navigation("DoorList");
                });
#pragma warning restore 612, 618
        }
    }
}
